"use client";

import Link from "next/link";

export default function SampleReportPage() {
  return (
    <div className="mx-auto max-w-5xl px-4 py-12 space-y-10">
      {/* HEADER */}
      <header className="space-y-3">
        <p className="text-[11px] font-semibold tracking-[0.22em] text-[#27E0C0] uppercase">
          Sample report
        </p>
        <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight">
          Example StrataHelix DNA wellness report
        </h1>
        <p className="text-sm sm:text-base text-[#9CA3AF] max-w-3xl">
          This is a fictional, non-medical example report showing the style, tone, and
          structure of a StrataHelix analysis. Real reports are generated by AI from
          your raw DNA file and are personalized to your genetic tendencies and goals.
        </p>
        <p className="text-[11px] text-[#6B7280]">
          Educational only. Not a medical service. No diagnoses, no disease risk
          predictions, and no treatment recommendations.
        </p>
      </header>

      {/* SUMMARY CARD */}
      <section className="grid gap-6 md:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)] items-start">
        <div className="rounded-xl border border-[#1F2933] bg-[#020617] p-6 space-y-3">
          <p className="text-xs font-semibold tracking-[0.18em] text-[#6B7280] uppercase">
            Executive snapshot
          </p>
          <h2 className="text-lg font-semibold text-[#F9FAFB]">
            Profile: strength-leaning hybrid responder with moderate carb tolerance.
          </h2>
          <p className="text-sm text-[#9CA3AF]">
            Your genetics suggest you respond well to structured strength training,
            slightly higher protein intake, and a consistent sleep-wake rhythm. You may
            benefit from moderating ultra-processed carbs, prioritizing high-quality
            protein, and building a repeatable training + recovery cadence.
          </p>
          <ul className="mt-2 space-y-1 text-xs text-[#D1D5DB]">
            <li>• Favors strength and hypertrophy with consistent training.</li>
            <li>• Moderate carb tolerance when paired with resistance work.</li>
            <li>• Sleep and circadian consistency are key performance levers.</li>
            <li>• Methylation & recovery pathways may benefit from targeted support.</li>
          </ul>
        </div>

        <div className="space-y-4 rounded-xl border border-[#1F2933] bg-[#020617] p-6">
          <p className="text-xs font-semibold text-[#D1D5DB]">
            How this sample report is structured
          </p>
          <ul className="space-y-2 text-[11px] text-[#9CA3AF]">
            <li>• Overview & key tendencies</li>
            <li>• Metabolism & nutrition</li>
            <li>• Training response & recovery</li>
            <li>• Sleep & circadian patterns</li>
            <li>• Stress, focus & mood</li>
            <li>• Methylation & recovery support (Methylation+ / Elite)</li>
            <li>• Supplement categories to consider (non-medical)</li>
            <li>• Example “daily rhythm” (Elite)</li>
          </ul>

          <div className="pt-2 space-y-2">
            <Link
              href="/upload?pkg=snapshot"
              className="inline-flex items-center justify-center rounded-md bg-[#27E0C0] px-4 py-2 text-xs font-medium text-[#020617] hover:opacity-90 transition"
            >
              Try a free Snapshot with your DNA
            </Link>
            <p className="text-[10px] text-[#6B7280]">
              You can start with a free Snapshot report using your raw DNA file, then
              upgrade to Core, Methylation+ or Elite if you want a deeper blueprint.
            </p>
          </div>
        </div>
      </section>

      {/* SECTION: METABOLISM */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Metabolism & nutrition tendencies
        </h2>
        <p className="text-sm text-[#9CA3AF]">
          Your genetic pattern suggests a moderate carb tolerance when carbs are paired
          with activity, plus a strong response to higher protein intake for body
          composition and satiety. This is not a diagnosis or strict macro prescription
          — it’s a directional map for experimentation.
        </p>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Likely tendencies
            </p>
            <ul className="space-y-1">
              <li>• Slightly higher appetite drive, especially under stress.</li>
              <li>• Better response to mixed meals (protein + complex carbs + fats).</li>
              <li>• Processed, low-fiber carbs more likely to lead to energy swings.</li>
              <li>• Protein-forward meals support body composition and fullness.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Practical levers to test
            </p>
            <ul className="space-y-1">
              <li>• Anchor each main meal around 25–40g of high-quality protein.</li>
              <li>• Bias carbs toward training days and earlier in the day.</li>
              <li>• Favor fiber-rich carbs (oats, potatoes, rice, fruit) over sweets.</li>
              <li>• Keep ultra-processed snacks as “sometimes tools,” not daily defaults.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* SECTION: TRAINING & RECOVERY */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Training response & recovery
        </h2>
        <p className="text-sm text-[#9CA3AF]">
          Your genetic profile points toward a hybrid responder: you likely gain the
          most from structured strength training, progressive overload, and a baseline
          of low-intensity movement (steps, incline walking) rather than constant HIIT.
        </p>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Training insights
            </p>
            <ul className="space-y-1">
              <li>• Responds well to 3–5 strength sessions per week.</li>
              <li>• Benefits from a blend of heavy compounds and moderate-rep work.</li>
              <li>• Too-frequent all-out HIIT may slow recovery and motivation.</li>
              <li>• Low-intensity steps / incline walking support fat loss and health.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Experiments to run
            </p>
            <ul className="space-y-1">
              <li>• Lock in 3–4 main strength days and treat them as non-negotiable.</li>
              <li>• Use 1–2 short conditioning blocks (bike sprints / finishers) weekly.</li>
              <li>• Track soreness, sleep, and performance to fine-tune volume.</li>
              <li>• Consider deload weeks every 6–8 weeks, especially under high life stress.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* SECTION: SLEEP & STRESS */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Sleep, circadian rhythm & stress
        </h2>
        <p className="text-sm text-[#9CA3AF]">
          Your genes suggest you may be more sensitive to sleep disruption and certain
          stimulants, and that you perform best when your sleep-wake schedule is
          consistent. Chronically short sleep is likely to impact mood, appetite, and
          training quality more noticeably for you.
        </p>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Likely sensitivities
            </p>
            <ul className="space-y-1">
              <li>• More sensitive to late-evening caffeine or bright light.</li>
              <li>• Noticeable mood / focus dips when sleep drops below ~7 hours.</li>
              <li>• Stress may amplify appetite and cravings if unchecked.</li>
              <li>• Wind-down routine strongly influences sleep quality.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Simple implementation ideas
            </p>
            <ul className="space-y-1">
              <li>• Keep caffeine earlier in the day, with a hard cutoff 6–8 hours before bed.</li>
              <li>• Aim for a consistent “lights down” window most nights.</li>
              <li>• Use 5–15 minutes of breath work, stretching, or low-stimulation reading before bed.</li>
              <li>• Treat late-night screens as a lever to pull back on during heavy training blocks.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* SECTION: METHYLATION & SUPPLEMENTS */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Methylation, recovery support & supplement categories
        </h2>
        <p className="text-sm text-[#9CA3AF]">
          In Methylation+ and Elite tiers, StrataHelix looks at patterns in genes that
          can influence methylation and recovery-related pathways (including common
          variants like MTHFR). We don’t diagnose or treat anything — instead we outline
          lifestyle and supplement categories that may deserve more attention.
        </p>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Lifestyle levers (non-medical)
            </p>
            <ul className="space-y-1">
              <li>• Emphasize leafy greens and colorful vegetables for natural folate.</li>
              <li>• Prioritize consistent sleep and recovery days to support repair.</li>
              <li>• Keep alcohol in a low-to-moderate range, not a daily default.</li>
              <li>• Regular movement and strength work to support cardio-metabolic health.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2 text-xs text-[#D1D5DB]">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Supplement categories to discuss with a professional
            </p>
            <ul className="space-y-1">
              <li>• Foundational: protein powder, creatine, high-quality multinutrient.</li>
              <li>• Methylation support: B-complex with active forms (e.g., methylated B12/folate).</li>
              <li>• Recovery: magnesium forms suited for sleep/muscle relaxation.</li>
              <li>• Stress & focus support: adaptogens or nootropic-style blends where appropriate.</li>
            </ul>
            <p className="text-[10px] text-[#6B7280]">
              These are categories, not prescriptions. Always align supplement use with
              your clinician’s guidance and your own lab work when available.
            </p>
          </div>
        </div>
      </section>

      {/* SECTION: DAILY RHYTHM (ELITE STYLE) */}
      <section className="space-y-3">
        <h2 className="text-lg font-semibold tracking-tight">
          Example daily rhythm (Elite-style overview)
        </h2>
        <p className="text-sm text-[#9CA3AF]">
          Elite reports include a “daily rhythm” view — not a rigid schedule, but an
          example of how to align training, nutrition, and recovery with your
          genetic tendencies and lifestyle constraints.
        </p>
        <div className="grid gap-4 md:grid-cols-3 text-xs text-[#D1D5DB]">
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              AM: Prime the system
            </p>
            <ul className="space-y-1">
              <li>• Wake at a consistent time; get natural light within 30–60 minutes.</li>
              <li>• Hydration + protein-forward breakfast or high-protein first meal.</li>
              <li>• Caffeine window earlier in the day, timed before deep work or training.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Training & mid-day
            </p>
            <ul className="space-y-1">
              <li>• Strength training or mixed session in your usual training window.</li>
              <li>• Carbs biased around training (pre/post) for performance and recovery.</li>
              <li>• Walks, steps, or light movement blocks between work sessions.</li>
            </ul>
          </div>
          <div className="rounded-lg border border-[#1F2933] bg-[#020617] p-4 space-y-2">
            <p className="text-[11px] font-semibold text-[#F9FAFB]">
              Evening: Downshift & repair
            </p>
            <ul className="space-y-1">
              <li>• Gradual light + screen fade-down 60–90 minutes before bed.</li>
              <li>• Protein + fiber-focused dinner, with heavy foods earlier in the evening.</li>
              <li>• Short wind-down ritual: stretching, reading, or breath work.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* CTA FOOTER */}
      <section className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#1F2933] bg-[#020617] px-6 py-5">
        <div className="space-y-1">
          <p className="text-sm font-semibold text-[#F9FAFB]">
            Ready to see your own StrataHelix report?
          </p>
          <p className="text-[11px] text-[#9CA3AF] max-w-xl">
            Start with a free Snapshot using your existing 23andMe or AncestryDNA file,
            or go straight to Core, Methylation+ or Elite if you already know you want
            the full blueprint.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link
            href="/upload?pkg=snapshot"
            className="inline-flex items-center justify-center rounded-md bg-[#27E0C0] px-4 py-2 text-xs font-medium text-[#020617] hover:opacity-90 transition"
          >
            Start free Snapshot
          </Link>
          <Link
            href="/pricing"
            className="inline-flex items-center justify-center rounded-md border border-[#374151] px-4 py-2 text-xs font-medium text-[#F9FAFB] hover:border-[#27E0C0]/80 transition"
          >
            View full pricing tiers
          </Link>
        </div>
      </section>
    </div>
  );
}
